"""Make Currency symbol unique

Revision ID: 9455ca15df6e
Revises: aeae2f66196f
Create Date: 2026-02-03 09:32:53.247378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9455ca15df6e'
down_revision: Union[str, Sequence[str], None] = 'aeae2f66196f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_symbol'), ['symbol'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_symbol'))

    # ### end Alembic commands ###
